version: '3'
services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    image: node_img
    container_name: portfolio-vue_node
    tty: true
    working_dir: /usr/src/app/
    volumes:
      - ./:/usr/src/app/
    environment:
      VUE_APP_API_ENDPOINT: ${VUE_APP_API_ENDPOINT}
    ports:
      - 8080:8080
      - 8000:8000
      - 3001:3001

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: portfolio-vue_web
    ports:
      - 80:80
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html